### PR TITLE
Fix build

### PR DESCRIPTION
**Pull request by groenroos**
Building this project resulted in a number of errors and warnings, and I found that the below changes fixed those.

- Set `package.json` explicitly to latest Stylus version
- Update `Makefile` with the correct CLI syntax to make the build run again
- Include lockfile for npm
- Add `Gemfile.lock` to `.gitignore` as per #30 - although wouldn't fixing the security alerts be preferable to deleting the lockfile? 🤔

### CODE REVIEW

**Comment by iChenLei** [comment]
cc @futekov
> To be honest, I want rebuild stylus-lang.com via docusaurus (or vuepress2) and add vercel(or netlify) auto deploy.

**Comment by groenroos** [comment]
> To be honest, I want rebuild stylus-lang.com via docusaurus (or vuepress2) and add vercel(or netlify) auto deploy.

I don't disagree - let me know if you want any help with that!

**Comment by futekov** [comment]
I don't see a need for rewriting the whole thing - would that actually solve any existing problems?

**Comment by iChenLei** [comment]
Add search (algolia), PWA support (offline reading), version control , i18n and more. Many aspects can be enhanced. @futekov 
> Of course, this is just my opinion

**Comment by iChenLei** [comment]
https://github.com/reactjs/reactjs.org/pull/3965

https://twitter.com/jaredpalmer/status/1451353773851381795?s=20

https://beta.reactjs.org/reference/usestate

https://twitter.com/leeerob/status/1451385721277796359?s=20



I think we can do the samething like react doc team, better ui, online stylus REPL (codepen or codesandbox) and more. and then publish https://beta.stylus-lang.com to collect feeedback.  cc @futekov @groenroos . I will start this work next month, when finish the new doc website prototype, i need @groenroos help me to do the rest work together, and then release beta.stylus-lang.com !  Hope things go as expected.

**Comment by groenroos** [comment]
@iChenLei I'd be interested to start working on the new site this week, even. What do you think would be the best way for us to write down a proper plan for what we want to do? Or should we just start writing issues?

**Comment by corysimmons** [comment]
@groenroos I'd close https://github.com/stylus/stylus-lang.com/issues/23 and begin tracking this entire project in a new Issue.

You can create a GitHub Project if you want but a docs site is a pretty quick/small project so it might not be needed--just get crackin'! 😀 

100% agree with @iChenLei's stack choice and reasons for doing it.

hmu if you guys need help with anything.

**Pull request merged**
