### PR TITLE
Updated Supported Logos

### PR DESCRIPTION
**Pull request by evilrabbit**
Added Auth0.com Logo and some styles fixes

screen shot 2015-09-07 at 4 27 21 pm

### CODE REVIEW

**Comment by corysimmons** [comment]
What is Auth0? Why would we add their logo?

**Comment by kizu** [comment]
Got a mail from Guillermo:

> Mind merging? They're big users of Stylus! Thanks a lot, hope all is good.

**Comment by kizu** [comment]
I think we could add a third section there to mention “big users of Stylus”, so there would be three sections overall: “Originated”, “Supported” and “Used at”. What do you think?

**Comment by evilrabbit** [comment]
Awesome! That would be great!

**Comment by corysimmons** [comment]
@iamevilrabbit Can you add a commit to do this and I'll merge?

**Comment by evilrabbit** [comment]
Cool. Let me design it first, and then if you like it, I will add a commit :)

**Comment by corysimmons** [comment]
:+1: Thanks evilrabbit

**Comment by corysimmons** [comment]
This LGTM. We should probably support large organizations that are using/promoting Stylus.

I'm going to go ahead and merge this, then clean up that entire area.

If we get more requests like this (or can track down more large orgs that use Stylus) we should break this out into its own section as @kizu suggested (I just don't think it makes sense to break it out for a single org right now).

**Comment by corysimmons** [comment]
Derp, overlooked this being merged into master. I'm going to be cleaning up that area in `gh-pages` in a second anyway, so I'll add Auth0's logo then.

**Pull request merged**
